Update cc component for vxworks

diff --git a/build/components/cc b/build/components/cc
--- a/build/components/cc
+++ b/build/components/cc
@@ -59,7 +59,7 @@ setCompilerOptions()
 
     if [ $hasGcc = 1 ] ; then
 
-        local defs="-D_VSB_CONFIG_FILE=\"vsbConfig.h\""
+        local vsb='#define _VSB_CONFIG_FILE "vsbConfig.h"'
 
         #
         #   Check if the compiler can handle -mtune. The tricky part 
@@ -69,16 +69,16 @@ setCompilerOptions()
         >${file}
         if [ "$verbose" != 0 ] ; then
             echo -e "    Checking for compiler -mtune support"
-            # echo -e "        ${cc}" $defs -Werror -arch ${cpu} -mtune=${cpu} -c $file "\n"
+            # echo -e "        ${cc}" -Werror -arch ${cpu} -mtune=${cpu} -c $file "\n"
         fi
 		eval tune=\$BLD_${KIND}_CFLAGS
 		tune=`echo $tune | sed 's/.*-mtune=//' | sed 's/ .*//'`
 		tune=${tune:=generic}
-        eval \"${cc}\" $defs -Werror -mtune=$tune -c $file >/dev/null 2>&1
+        eval \"${cc}\" -Werror -mtune=$tune -c $file >/dev/null 2>&1
         if [ $? = 0 ] ; then
             eval $hasMtune=1
 		else
-			eval \"${cc}\" $defs -Werror -Wall -mtune=${cpu} -c $file >/dev/null 2>&1
+			eval \"${cc}\" -Werror -Wall -mtune=${cpu} -c $file >/dev/null 2>&1
 			if [ $? = 0 ] ; then
 				eval $hasMtune=1
 			fi
@@ -89,9 +89,9 @@ setCompilerOptions()
         #
         if [ "$verbose" != 0 ] ; then
             echo -e "    Checking for compiler -fno-stack-protector support"
-            # echo -e "        ${cc}" $defs -Werror -Wall -fno-stack-protector -c $file "\n"
+            # echo -e "        ${cc}" -Werror -Wall -fno-stack-protector -c $file "\n"
         fi
-        eval \"${cc}\" $defs -Werror -Wall -fno-stack-protector -c $file >/dev/null 2>&1
+        eval \"${cc}\" -Werror -Wall -fno-stack-protector -c $file >/dev/null 2>&1
         if [ $? = 0 ] ; then
             eval $hasStackProtector=1
         fi
@@ -101,16 +101,16 @@ setCompilerOptions()
         #
         if [ "$verbose" != 0 ] ; then
             echo -e "    Checking for compiler -Wno-unused-result support"
-            # echo -e "        ${cc}" $defs -Werror -Wall -Wno-unused-result -c $file "\n"
+            # echo -e "        ${cc}" -Werror -Wall -Wno-unused-result -c $file "\n"
         fi
-        echo -e "#include <stdio.h>\n#include <stdlib.h>\nint main() { realloc(0, 1024); return 0; }\n" >$file
+        echo -e "$vsb\n#include <stdio.h>\n#include <stdlib.h>\nint main() { realloc(0, 1024); return 0; }\n" >$file
         #
         #   Test that it passes with -Wno-unused-result and that it fails without it
         #   Needs optimization to trigger on most systems
         #
-        eval \"${cc}\" $defs -Os -Werror -Wall -Wno-unused-result -c $file >/dev/null 2>&1
+        eval \"${cc}\" -Os -Werror -Wall -Wno-unused-result -c $file >/dev/null 2>&1
         if [ $? = 0 ] ; then
-            eval \"${cc}\" $defs -Os -Werror -Wall -c $file >/dev/null 2>&1
+            eval \"${cc}\" -Os -Werror -Wall -c $file >/dev/null 2>&1
             if [ $? != 0 ] ; then
                 eval $hasWarnUnused=1
             fi
@@ -121,9 +121,9 @@ setCompilerOptions()
         #
         if [ "$verbose" != 0 ] ; then
             echo -e "    Checking for compiler -Wshorten-64-to-32 support"
-            # echo -e "        ${cc}" $defs -Werror -Wall -Wshorten-64-to-32 -c $file "\n"
+            # echo -e "        ${cc}" -Werror -Wall -Wshorten-64-to-32 -c $file "\n"
         fi
-        eval \"${cc}\" $defs -Werror -Wall -Wshorten-64-to-32 -c $file >/dev/null 2>&1
+        eval \"${cc}\" -Werror -Wall -Wshorten-64-to-32 -c $file >/dev/null 2>&1
         if [ $? = 0 ] ; then
             eval $hasWarn64to32=1
         fi
@@ -133,10 +133,10 @@ setCompilerOptions()
         #
         if [ "$verbose" != 0 ] ; then
             echo -e "    Checking for initializers"
-            # echo "         ${cc}" $defs -o $out -c $file 
+            # echo "         ${cc}" -o $out -c $file 
         fi
-        echo -e "#include <stdarg.h>\nva_list d = {{0}};\n" >$file
-        eval \"${cc}\" $defs ${flags} -Werror -Wall -c -o $out -c $file >/dev/null 2>&1
+        echo -e "$vsb\n#include <stdarg.h>\nva_list d = {{0}};\n" >$file
+        eval \"${cc}\" ${flags} -Werror -Wall -c -o $out -c $file >/dev/null 2>&1
         if [ $? = 0 ] ; then
             eval $hasDoubleBraces=1
         fi
@@ -146,11 +146,12 @@ setCompilerOptions()
         #
         if [ "$verbose" != 0 ] ; then
             echo -e "    Checking for builtin sync primitives"
-            # echo "         ${cc}" $defs -o $out -c $file 
+            # echo "         ${cc}" -o $out -c $file 
         fi
-        echo -e "#include <stdio.h>\nint main() { __sync_synchronize(); return 0; }\n" >$file
-        eval \"${cc}\" $defs ${flags} -Werror -Wall -c -o $out -c $file >/dev/null 2>&1
-        if [ $? = 0 ] ; then
+        echo -e "$vsb\n#include <stdio.h>\nint main() { __sync_synchronize(); return 0; }\n" >$file
+        eval \"${cc}\" ${flags} -Werror -Wall -c -o $out -c $file >/dev/null 2>&1
+        rc=$?
+        if [ $rc = 0 ] ; then
             eval $hasSync=1
         fi
 
@@ -160,10 +161,10 @@ setCompilerOptions()
             #
             if [ "$verbose" != 0 ] ; then
                 echo -e "    Checking for fork()"
-                # echo -e "        ${cc}" $defs -o $out -c $file "\n"
+                # echo -e "        ${cc}" -o $out -c $file "\n"
             fi
-            echo -e "#include <stdio.h>\n#include <unistd.h>\nint main() { fork(); return 0; }\n" >$file
-            eval \"${cc}\" $defs ${flags} -o $out $file >/dev/null 2>&1
+            echo -e "$vsb\n#include <stdio.h>\n#include <unistd.h>\nint main() { fork(); return 0; }\n" >$file
+            eval \"${cc}\" ${flags} -o $out $file >/dev/null 2>&1
             if [ $? = 0 ] ; then
                 eval $hasMmu=1
             fi
@@ -176,14 +177,14 @@ setCompilerOptions()
             #
             if [ "$verbose" != 0 ] ; then
                 echo -e "    Checking for dlopen()"
-                # echo "         ${cc}" $defs -o $out -c $file 
+                # echo "         ${cc}" -o $out -c $file 
             fi
-            echo -e "#include <stdio.h>\n#include <dlfcn.h>\nint main() { dlopen(\"test.so\", 0); return 0; }\n" >$file
-            eval \"${cc}\" $defs ${flags} -o $out $file >/dev/null 2>&1
+            echo -e "$vsb\n#include <stdio.h>\n#include <dlfcn.h>\nint main() { dlopen(\"test.so\", 0); return 0; }\n" >$file
+            eval \"${cc}\" ${flags} -o $out $file >/dev/null 2>&1
             if [ $? = 0 ] ; then
                 eval $hasDynLoad=1
             else
-                eval \"${cc}\" $defs ${flags} -o $out $file -ldl >/dev/null 2>&1
+                eval \"${cc}\" ${flags} -o $out $file -ldl >/dev/null 2>&1
                 if [ $? = 0 ] ; then
                     eval $hasDynLoad=1
                 fi
@@ -194,10 +195,10 @@ setCompilerOptions()
             #
             if [ "$verbose" != 0 ] ; then
                 echo -e "    Checking for libedit()"
-                # echo "         ${cc}" $defs -o $out -c $file 
+                # echo "         ${cc}" -o $out -c $file 
             fi
-            echo -e "#include <histedit.h>\nint main() { history_init(); return 0; }\n" >$file
-            eval \"${cc}\" $defs ${flags} -o $out $file -ledit -lcurses >/dev/null 2>&1
+            echo -e "$vsb\n#include <histedit.h>\nint main() { history_init(); return 0; }\n" >$file
+            eval \"${cc}\" ${flags} -o $out $file -ledit -lcurses >/dev/null 2>&1
             if [ $? = 0 ] ; then
                 eval $hasLibEdit=1
             fi
@@ -207,24 +208,23 @@ setCompilerOptions()
             #
             if [ "$verbose" != 0 ] ; then
                 echo -e "    Checking for libpam()"
-                # echo "         ${cc}" $defs -o $out -c $file 
+                # echo "         ${cc}" -o $out -c $file 
             fi
-            echo -e "extern pam_start(); \nint main() { void *x = pam_start; return 0; }\n" >$file
-            eval \"${cc}\" $defs ${flags} -o $out $file -lpam >/dev/null 2>&1
+            echo -e "$vsb\nextern pam_start(); \nint main() { void *x = pam_start; return 0; }\n" >$file
+            eval \"${cc}\" ${flags} -o $out $file -lpam >/dev/null 2>&1
             if [ $? = 0 ] ; then
                 eval $hasPam=1
             fi
-
 
             #
             #   Unnamed unions
             #
             if [ "$verbose" != 0 ] ; then
                 echo -e "    Checking for unnamed union support"
-                # echo "         ${cc}" $defs -o $out -c $file 
+                # echo "         ${cc}" -o $out -c $file 
             fi
-            echo -e "#include <stdio.h>\nint main() { struct test { union { int x; int y; };}; return 0; }\n" >$file
-            eval \"${cc}\" $defs ${flags} -Werror -Wall -c -o $out -c $file >/dev/null 2>&1
+            echo -e "$vsb\n#include <stdio.h>\nint main() { struct test { union { int x; int y; };}; return 0; }\n" >$file
+            eval \"${cc}\" ${flags} -Werror -Wall -c -o $out -c $file >/dev/null 2>&1
             if [ $? = 0 ] ; then
                 eval $hasUnnamedUnions=1
             fi
